export default {
  emailFieldName: "os_username",
  passwordFieldName: "os_password",
  loginDialog: "#login-form ",
  loginSubmit: "#login-form-submit ",
  lxpTabId: "a#link-issue-tab-panel ",
  yourWorkContainer: "[data-test-id='global-pages.home.ui.home'] ",
  lxpContainerRoot: "#lxp-container-root ",
  lxpTreeContainer: ".lxp-tree ",
  lxpTreeItem: ".lxp-tree-item ",
  priorityDropdown: "#priorities-dropdown ",
  linkTypeDropdown: "#linkTypes-dropdown ",
  issueTypeDropdown: "#issueTypes-dropdown ",
  clearAllClassName: ".clear-btn",
  selectAllClassName: ".selectall-btn",
  issueKeyClassName: ".item-key",
  issueCardFieldsDropdown: "#issue-card-fields-dropdown ",
  expandAllButton: "#expand-all-btn",
  collapseAllButton: "#collapse-all-btn ",
  exportCSVButton: "#export-csv-btn ",
  helpLinkButton: "#help-link-btn ",
};